<a href="https://colab.research.google.com/github/JosueSandovalZT/Unidad-5/blob/main/Tabla_de_diferencias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio 1 - Tabla de diferencias

---



In [2]:
import numpy as np # importa numpy para manejo de arreglos y operaciones

x  = np.array([1,2,3]) # define los valores de x conocidas
y  = np.array([1,4,9]) # define los valoes de y conocidas

n = len(x) # calcula el numero de puntos

tabla = np.zeros((n,n)) # inicializa la tabla de diferencias divididas

tabla[:,0] = y #llena la primera columna con los valores de y

for j in range(1,n): #itera sobre las columnas de la tabla
    for i in range(n-j): #itera sobre las filas disponibles
        tabla [i,j] = (tabla[i+1,j-1] - tabla[i,j-1]) / (x[i+j] -x[i]) # calcula la diferencia

print("tabla de diferencias dividias : \n" ,tabla)# muestra la tabla

tabla de diferencias dividias : 
 [[1. 3. 1.]
 [4. 5. 0.]
 [9. 0. 0.]]
